function checkMinimizeVersion()

%% check that the users version of minimize is Carl Rasmussen's latest

try
    numIter=0;    
    [newZ, fval] = minimize(0,'testMinimizeFunction',numIter,...
       1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25);
catch     
     warnStr=sprintf(...
         ['****************************************************************\n'...
         'You do not have the latest version of minimize.m\n'...
         'Please visit http://www.kyb.tuebingen.mpg.de/bs/people/carl/code/minimize/minimize.m\n'...
         '(I recommend commenting out the fprintf statements)\n'...
         '****************************************************************'...
         ]);
     error(warnStr);    
end

return;


