function checkMaxSparseMEX()

if exist('maxSparseMEX')~=3
     warnStr=sprintf(...
         ['****************************************************************\n'...
         'You need to compile the MEX function: maxSparseMEX.c\n'...
         'Use something like this at the command prompt: \n'...
         '>> mex maxSparseMEX.c\n'...
         '(first, inside of Matlab, go to the directory in which this file lies\n'...
         ' and it lies inside of CPM_code_v1.0/cpm_functions/MEX/)\n'...
         '****************************************************************'...
         ]);
     error(warnStr);
end
