function fieldList = getGfields()

fieldList = {'saveIterFile' 'thresh' 'maxIter' ...
    'updateSigma', 'updateU' 'updateZ' ...
    'updateScale' 'updateTime' 'oneScaleOnly' ...
    'numBins' 'lambda' 'nu' ...
    'useLogZ', 'numSamples', 'numRealTimes', 'numTaus', ...
    'numScales', 'numStates', 'S', 'pseudoS', 'pseudoT', ...
    'extraPercent', 'scales', 'w', 'numClass', 'maxTimeSteps', ...
    'startSamp', 'sigFrac' ...
    'numCtrlPts', 'cntrlPts' 'USE_CPM2' 'SHARE_TRANS' ...
    'ONE_CLASS' 'USE_GLOBAL_U' 'USE_HBCPM' 'SHARE' 'ukV'...
    'zInitType' 'fixedClasses' 'SMART_INIT_ZP' 'smartInitNumIter'};


