function savevars = getSaveVars()

savevars = ['iterG allTocs trainSetInd testSetInd datName myDir '...
    ' testNumIt trainNumIt lambda finalTraces allGtest allGtrain '... 
    ' finalTraces holdOutLL myThresh smooth nu updateScale '...
    'updateSigma updateT updateZ numBins ALTERNATE_BINS BLUR '...
    'timeBlur mzBlur useHoldOut scaleAndTimesTrain '...
    'scaleAndTimesTest USE_BP'];
